### ISSUE TITLE
Failed to translate 'semantic-ui-react'

### ISSUE THREAD

**Issue by alxgrk** [Kotlin/dukat#207] opened 2019-12-19 22:47 UTC
I tried to convert [semantic-ui-react](https://github.com/Semantic-Org/Semantic-UI-React) typings using kotlin gradle plugin, with `kotlin.js.experimental.generateKotlinExternals=true` turned on and dukat version set to `0.0.24`.
I was also able to reproduce the error using dukat/0.0.24 directly like so: 
`dukat node_modules/semantic-ui-react/index.d.ts`.
```
.../node_modules/dukat/lib/converter.js:128828
        var packageNameFragments = sourceFile.fileName.split("/");
                                              ^

TypeError: Cannot read property 'fileName' of undefined
    at AstConverter.createSourceFileDeclaration (.../node_modules/dukat/lib/converter.js:128828:47)
    at SourceBundleBuilder.createFileDeclarations (.../node_modules/dukat/lib/converter.js:162:44)
    at .../node_modules/dukat/lib/converter.js:167:19
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (.../node_modules/dukat/lib/converter.js:166:14)
    at .../node_modules/dukat/lib/converter.js:167:19
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (.../node_modules/dukat/lib/converter.js:166:14)
    at .../node_modules/dukat/lib/converter.js:167:19
    at Array.forEach (<anonymous>)
```

**Comment by hshar7** [comment] 2020-01-06 16:35
Any news?

**Comment by domfranke** [comment] 2020-01-08 13:37
The same problem happens when trying to convert Atlaskit Button (https://www.npmjs.com/package/@atlaskit/button)

I used this dependency in my gradle file
`implementation npm('@atlaskit/button', '^13.3.4')`

**Comment by fjf2002** [comment] 2020-01-16 09:18
The same problem when I include the npm library apollo-client, using dukat version 0.0.25

**Comment by xian** [comment] 2020-02-03 18:46
Same for `querystring:0.2.0`.

**Comment by epabst** [comment] 2020-02-11 14:30
Same for `twilio:3.39.4`

**Comment by justjake** [comment] 2020-02-26 19:13
This is broken for me with a small, self-generated `.d.ts` file.

**Comment by NickAcPT** [comment] 2020-03-04 00:23
Same for `monaco-languageclient:0.11.0` using dukat 0.0.28.

Is there any kind of workaround for this? I'm unable to use `generateKotlinExternals` because it keeps erroring on the languageclient depend.

**Comment by joffrey-bion** [comment] 2020-03-21 16:35
Same problem with `@blueprintjs/core` using Dukat 0.0.28, running it manually against `lib/esm/index.d.ts`

**Comment by tjuricek-vmware** [comment] 2020-03-29 16:03
Looks like there's the same problem for `electron`. 

I've got a _minimal_ project, just tried using the new 1.4-M1 build with the IR backend and 1.3.71, and it's the same result.

This was run using Gradle 6.3:

````
/home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:472
        return this.astFactory.createSourceFileDeclaration(sourceFile.fileName, this.createModuleFromSourceFile(sourceFile));
                                                                      ^
TypeError: Cannot read property 'fileName' of undefined
    at AstConverter.createSourceFileDeclaration (/home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:472:71)
    at SourceBundleBuilder.createFileDeclarations (/home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:169:49)
    at /home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:177:23
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (/home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:176:18)
    at /home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:177:23
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (/home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:176:18)
    at /home/tjuricek/dev/tjuricek/project-docs/build/js/node_modules/dukat/lib/converter.js:177:23
    at Array.forEach (<anonymous>)

FAILURE: Build failed with an exception.
````

Just for reference, the dependencies are stupidly small:

````
dependencies {
    implementation(kotlin("stdlib-js"))
    implementation(npm("electron", "8.2.0"))
}
````

I may be doing something wrong, as I'm _very_ new to Kotlin/JS in general.

**Comment by NickAcPT** [comment] 2020-05-09 20:32
This is a somewhat breaking bug. Multiple stack traces were posted. Has this been looked at yet?

**Comment by IARI** [comment] 2020-05-18 18:06
i get the same error, running dukat on any d.ts file.

**Comment by IARI** [comment] 2020-05-18 18:28
Ok - apparently, this has something to do with the source file location for me.
As soon as i moved the `.d.ts` sourcefiles from a location

>  D:\github\<myProjectName>\build\js\node_modules\formik\dist\ErrorMessage.d.ts

To the location

> E:\Documents\dukattest

it works for me.

**Comment by set321go** [comment] 2020-05-18 20:38
In my case this was caused by `/// <reference types="node" />` in the file i was attempting to convert, removing this line allowed me to successfully generate the kotlin files (but it doesn't compile because its missing the referenced type). The lib i'm trying to convert just references the `Buffer` type so modifying the reference to `/// <reference types="../node/buffer.d.ts" />` (it was already pulled in as a dep by the type lib) also worked.

**Comment by Schahen** [comment] 2020-05-29 22:58
In dukat@0.5.0 the problem with failing to translate is gone. I see some issues with code translate which will be addressed (and some of them are in work already) so I'm closing this one.

**Closed by Schahen** 2020-05-29 22:58 UTC
